Fix issue with grid files larger than 2G
- As reported in Issue #4 for resolutions finer than 1/12 degree the resulting grid file is larger than 2GB
  causing the tool to crash with:
  File "netCDF4/_netCDF4.pyx", line 4648, in netCDF4._netCDF4.Variable.__setitem__
  File "netCDF4/_netCDF4.pyx", line 4913, in netCDF4._netCDF4.Variable._put
  File "netCDF4/_netCDF4.pyx", line 1754, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Operation not allowed in define mode

- Changing format=NETCDF3_CLASSIC to NETCDF3_64BIT fixes this issue